# -*- coding: utf-8 -*-
"""HybridRAG_Multi-HopRAG_ContextualRAG_Gemini_FlanT5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kB77_Yf-dqSygTnu2qa_qtf2ZEwwO2GS
"""

# !pip install faiss-cpu pandas langchain sentence-transformers transformers google-generativeai fastapi uvicorn

# !pip install langchain-community

import faiss
import pandas as pd
import numpy as np
from langchain_community.vectorstores import FAISS
from langchain_huggingface import HuggingFaceEmbeddings
from transformers import T5Tokenizer, T5ForConditionalGeneration
import google.generativeai as genai
from fastapi import FastAPI
import os
from langchain_community.docstore.in_memory import InMemoryDocstore

# Initialize FastAPI app
app = FastAPI()

genai.configure(api_key="AIzaSyByJNTAhlH7jiLbQIm94ovG39rNK-LfXoA")
gemini_model = genai.GenerativeModel("models/gemini-2.5-flash")  # Correct way to call Gemini

# Load pre-trained embeddings model
embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")

# Initialize FAISS index
vector_dim = 384  # Dimensionality of embedding model
faiss_index_path = "faiss_index"

if os.path.exists(faiss_index_path):
    vectorstore = FAISS.load_local(
        faiss_index_path,
        embeddings,
        allow_dangerous_deserialization=True
    )
else:
    index = faiss.IndexFlatL2(vector_dim)

    # Create an empty docstore and index mapping
    docstore = InMemoryDocstore({})
    index_to_docstore_id = {}

    # Correct FAISS initialization
    vectorstore = FAISS(embedding_function=embeddings, index=index, docstore=docstore, index_to_docstore_id=index_to_docstore_id)

def ingest_csv_to_faiss(csv_file):
    """Reads a CSV file and updates FAISS with embeddings."""
    df = pd.read_csv(csv_file)

    new_vectors_text = embeddings.embed_documents(df["text"].tolist())
    vectorstore.add_texts(df["text"].tolist(), embeddings=new_vectors_text)
    vectorstore.save_local(faiss_index_path)
    print(f"{len(df)} new text articles added to FAISS!")

    new_vectors_summary = embeddings.embed_documents(df["summary"].tolist())
    vectorstore.add_texts(df["summary"].tolist(), embeddings=new_vectors_summary)
    vectorstore.save_local(faiss_index_path)
    print(f"{len(df)} new summary articles added to FAISS!")

"""# Multi-Hop RAG"""

def retrieve_documents(query, k=5):
    """Retrieves k most relevant news articles from FAISS"""
    return vectorstore.similarity_search(query, k=k)


def generate_answer_with_gemini(docs, query):
    """Generates an answer using Gemini with retrieved documents."""
    context = "\n".join([doc.page_content for doc in docs])
    input_text = f"Answer the query based on the provided documents.\n\nContext:\n{context}\n\nQuery: {query}\nAnswer:"
    response = gemini_model.generate_content(input_text)
    return response.text.strip()


def gemini_rag_pipeline(query):
    """Pipeline using only Gemini for retrieval ranking & answer generation"""
    retrieved_docs = retrieve_documents(query)
    final_answer = generate_answer_with_gemini(retrieved_docs, query)
    return final_answer

def build_summary_prompt(report: dict, mode="concise"):
    if mode == "concise":
        instruction = (
            "Generate a concise 2–3 sentence summary suitable for a dashboard."
        )
    else:
        instruction = (
            "Generate a detailed operational report explaining key metrics, "
            "issues, and insights."
        )

    return f"""
You are an AI that summarizes structured system reports.

{instruction}

Report (JSON):
{report}

Summary:
"""

def summarize_report(report: dict, mode="concise"):
    prompt = build_summary_prompt(report, mode)
    response = gemini_model.generate_content(prompt)
    return response.text.strip()